# Generated by Django 5.2.11 on 2026-02-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cameratype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('brand_materi', models.CharField(max_length=200, verbose_name='Brand / Materi')),
                ('lokasi', models.CharField(max_length=200, verbose_name='Lokasi')),
                ('tanggal', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('pic_pemohon', models.CharField(max_length=150, verbose_name='PIC Pemohon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jenis_kamera', models.ManyToManyField(to='products.cameratype', verbose_name='Jenis Kamera')),
                ('jenis_led', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ledtype', verbose_name='Jenis LED')),
                ('requirements', models.ManyToManyField(to='products.requirement', verbose_name='Requirements')),
                ('view_photo', models.ManyToManyField(to='products.viewphoto', verbose_name='View Photo')),
            ],
        ),
    ]
