# Generated by Django 5.2.11 on 2026-03-05 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ledtype_requirement_viewphoto_documentationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentationrequest',
            name='email',
        ),
        migrations.AddField(
            model_name='documentationrequest',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doc_requests', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
            preserve_default=False,
        ),
    ]
