# Generated by Django 5.2.11 on 2026-03-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_documentationrequest_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
