# Generated by Django 5.2.11 on 2026-03-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationrequest',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'On Progress'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
    ]
