# Generated by Django 5.2.11 on 2026-03-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brandmateri_lokasi_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumentator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documentationrequest',
            name='brand_materi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brandmateri', verbose_name='Brand / Materi'),
        ),
        migrations.AlterField(
            model_name='documentationrequest',
            name='lokasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.lokasi', verbose_name='Lokasi'),
        ),
        migrations.AddField(
            model_name='documentationrequest',
            name='pelaksana',
            field=models.ManyToManyField(blank=True, to='products.dokumentator', verbose_name='Pelaksana Dokumentasi'),
        ),
    ]
