# Generated by Django 5.2.11 on 2026-03-18 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_edithistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NamaPerangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('group', models.CharField(choices=[('MING', 'Inventory MING'), ('MOBILE_LED', 'Inventory Mobile LED'), ('MST', 'Inventory MST'), ('LUMINOVA', 'Inventory Luminova')], max_length=20)),
            ],
            options={
                'ordering': ['group', 'name'],
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemohon', models.CharField(max_length=150, verbose_name='Nama Pemohon')),
                ('departement', models.CharField(max_length=150, verbose_name='Departement')),
                ('tanggal_permintaan', models.DateField(verbose_name='Tanggal Permintaan')),
                ('tanggal_deadline', models.DateField(verbose_name='Tanggal Deadline')),
                ('deskripsi_pekerjaan', models.TextField(verbose_name='Deskripsi Pekerjaan')),
                ('foto_kerusakan', models.ImageField(upload_to='maintenance_photos/', verbose_name='Foto Kerusakan')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'On Progress'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_items', models.ManyToManyField(blank=True, to='products.inventoryitem', verbose_name='Inventory')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maint_requests', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
                ('nama_perangkat', models.ManyToManyField(to='products.namaperangkat', verbose_name='Nama Perangkat')),
            ],
        ),
    ]
