# Generated by Django 5.2.11 on 2026-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_namaperangkat_inventoryitem_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='foto_kerusakan',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_photos/', verbose_name='Foto Kerusakan'),
        ),
    ]
