# Generated by Django 5.2.11 on 2026-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_maintenancerequest_foto_kerusakan'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='pelaksana',
            field=models.ManyToManyField(blank=True, to='products.dokumentator', verbose_name='Pelaksana Maintenance'),
        ),
    ]
