# Generated by Django 5.2.11 on 2026-03-30 04:08

from django.db import migrations, models


def copy_existing_lokasi_to_m2m(apps, schema_editor):
    DocumentationRequest = apps.get_model('products', 'DocumentationRequest')
    db_alias = schema_editor.connection.alias
    through_model = DocumentationRequest.lokasi_multi.through

    for doc_request in DocumentationRequest.objects.using(db_alias).exclude(lokasi_id=None).iterator():
        through_model.objects.using(db_alias).get_or_create(
            documentationrequest_id=doc_request.id,
            lokasi_id=doc_request.lokasi_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_maintenancerequest_pelaksana'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationrequest',
            name='jenis_lokasi',
            field=models.CharField(choices=[('SINGLE', 'Single Lokasi'), ('MULTI', 'Multi Lokasi')], default='SINGLE', max_length=10, verbose_name='Jenis Lokasi'),
        ),
        migrations.AddField(
            model_name='documentationrequest',
            name='lokasi_multi',
            field=models.ManyToManyField(blank=True, related_name='+', to='products.lokasi', verbose_name='Lokasi'),
        ),
        migrations.RunPython(copy_existing_lokasi_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='documentationrequest',
            name='lokasi',
        ),
        migrations.RenameField(
            model_name='documentationrequest',
            old_name='lokasi_multi',
            new_name='lokasi',
        ),
        migrations.AlterField(
            model_name='documentationrequest',
            name='lokasi',
            field=models.ManyToManyField(to='products.lokasi', verbose_name='Lokasi'),
        ),
    ]
