# Generated by Django 5.2.11 on 2026-03-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_set_jenis_lokasi_from_lokasi_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentationrequest',
            name='jenis_lokasi',
        ),
    ]
