# Generated by Django 5.2.11 on 2026-03-31 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_documentationrequest_jenis_lokasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalTayang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tayang', models.DateTimeField(verbose_name='Tanggal Tayang')),
                ('tanggal_takeout', models.DateTimeField(verbose_name='Tanggal Takeout')),
                ('note_requester', models.TextField(blank=True, verbose_name='Notes Requester')),
                ('note_executor', models.TextField(blank=True, verbose_name='Notes Executor')),
                ('pic_pemohon', models.CharField(max_length=150, verbose_name='PIC Pemohon')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'On Progress'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_materi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brandmateri', verbose_name='Brand / Materi')),
                ('jenis_led', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ledtype', verbose_name='Jenis LED')),
                ('lokasi', models.ManyToManyField(to='products.lokasi', verbose_name='Lokasi')),
                ('pelaksana', models.ManyToManyField(blank=True, related_name='jadwal_tayang_assignments', to='products.dokumentator', verbose_name='Pelaksana')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_tayang_requests', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JadwalTayangBuktiPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_pagi', models.ImageField(blank=True, null=True, upload_to='jadwal_tayang/playlist/', verbose_name='Bukti Playlist Pagi')),
                ('foto_siang', models.ImageField(blank=True, null=True, upload_to='jadwal_tayang/playlist/', verbose_name='Bukti Playlist Siang')),
                ('foto_malam', models.ImageField(blank=True, null=True, upload_to='jadwal_tayang/playlist/', verbose_name='Bukti Playlist Malam')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('jadwal_tayang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bukti_playlist', to='products.jadwaltayang')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalTayangFotoTakeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='jadwal_tayang/takeout/', verbose_name='Foto Takeout')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('jadwal_tayang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_takeout_set', to='products.jadwaltayang')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JadwalTayangFotoTayang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='jadwal_tayang/tayang/', verbose_name='Foto Tayang')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('jadwal_tayang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_tayang_set', to='products.jadwaltayang')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
