# Generated by Django 5.2.11 on 2026-03-31 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_create_role_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationrequest',
            name='jenis_led',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ledtype', verbose_name='Jenis Produk'),
        ),
        migrations.AlterField(
            model_name='jadwaltayang',
            name='jenis_led',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ledtype', verbose_name='Jenis Produk'),
        ),
        migrations.AlterField(
            model_name='jadwaltayang',
            name='status',
            field=models.CharField(choices=[('BELUM_TAYANG', 'Belum Tayang'), ('SEDANG_TAYANG', 'Sedang Tayang'), ('SUDAH_TAKEOUT', 'Sudah Takeout')], default='BELUM_TAYANG', max_length=20),
        ),
    ]
