# Generated by Django 5.2.11 on 2026-03-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_documentationrequest_jenis_led_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edithistory',
            name='request_type',
            field=models.CharField(choices=[('DOC_REQUEST', 'Documentation Request'), ('JADWAL_TAYANG', 'Jadwal Tayang')], default='DOC_REQUEST', max_length=20),
        ),
    ]
