# Generated by Django 5.2.11 on 2026-03-31 04:17

from django.db import migrations, models


def seed_default_takeout_alert_rules(apps, schema_editor):
    TakeoutAlertRule = apps.get_model('products', 'TakeoutAlertRule')
    defaults = [
        {
            'name': 'H-1 Warning',
            'offset_unit': 'DAY',
            'offset_value': 1,
            'lead_minutes': 1440,
            'urgency': 'WARNING',
            'is_active': True,
        },
        {
            'name': 'Jam-6 Urgent',
            'offset_unit': 'HOUR',
            'offset_value': 6,
            'lead_minutes': 360,
            'urgency': 'URGENT',
            'is_active': True,
        },
    ]
    for rule_data in defaults:
        TakeoutAlertRule.objects.get_or_create(name=rule_data['name'], defaults=rule_data)


def remove_default_takeout_alert_rules(apps, schema_editor):
    TakeoutAlertRule = apps.get_model('products', 'TakeoutAlertRule')
    TakeoutAlertRule.objects.filter(name__in=['H-1 Warning', 'Jam-6 Urgent']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_edithistory_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeoutAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('offset_unit', models.CharField(choices=[('DAY', 'Hari'), ('HOUR', 'Jam')], max_length=10)),
                ('offset_value', models.PositiveIntegerField()),
                ('lead_minutes', models.PositiveIntegerField(default=0, editable=False)),
                ('urgency', models.CharField(choices=[('WARNING', 'Warning'), ('URGENT', 'Urgent')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Takeout Alert Rule',
                'verbose_name_plural': 'Takeout Alert Rules',
                'ordering': ['-is_active', '-lead_minutes', 'urgency', 'name'],
            },
        ),
        migrations.RunPython(seed_default_takeout_alert_rules, remove_default_takeout_alert_rules),
    ]
