# Generated by Django 5.2.11 on 2026-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_takeoutalertrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="takeoutalertrule",
            name="trigger_direction",
            field=models.CharField(
                choices=[("BEFORE", "Sebelum Takeout"), ("AFTER", "Sesudah Takeout")],
                default="BEFORE",
                max_length=10,
            ),
        ),
    ]
