# Generated by Django 4.2.29 on 2026-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_userloginrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationrequest',
            name='foto_bukti_kerja',
            field=models.ImageField(blank=True, null=True, upload_to='doc_request_proofs/', verbose_name='Foto Bukti Kerja'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='foto_bukti_kerja',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_proofs/', verbose_name='Foto Bukti Kerja'),
        ),
    ]
