# Generated by Django 4.2.29 on 2026-04-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_documentationrequest_foto_bukti_kerja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='brand_materi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brandmateri', verbose_name='Brand / Materi'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='jenis_led',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ledtype', verbose_name='Jenis Produk'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='lokasi',
            field=models.ManyToManyField(blank=True, to='products.lokasi', verbose_name='Lokasi'),
        ),
    ]
