# Generated by Django 4.2.29 on 2026-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_maintenancerequest_brand_materi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='jenis_led',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='nama_perangkat',
            field=models.ManyToManyField(to='products.namaperangkat', verbose_name='Jenis Produk'),
        ),
    ]
