# Generated by Django 4.2.29 on 2026-05-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_materi_proof_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationrequestlokasiassignment',
            name='perintah_kerja',
            field=models.TextField(blank=True, default='', verbose_name='Perintah Kerja'),
        ),
    ]
